const types = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
    LOGIN_REQUEST_ERROR: "LOGIN_REQUEST_ERROR",

    // REGISTER_USER: "REGISTER_USER",
    // REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    // REGISTER_USER_ERROR: "REGISTER_USER_ERROR"    
}

export default types