const types = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
  LOGIN_REQUEST_ERROR: "LOGIN_REQUEST_ERROR",

  COINS_MARKETS_REQUEST: "COINS_MARKETS_REQUEST",
  COINS_MARKETS_SUCCESS: "COINS_MARKETS_SUCCESS",
  COINS_MARKETS_ERROR: "COINS_MARKETS_ERROR"
};

export default types;
